# Generated by Django 5.1.1 on 2024-09-13 04:49

import django.db.models.deletion
import django_choices_field.fields
import example.fruit.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(help_text="The colour name", max_length=20, verbose_name="name")),
            ],
            options={
                "verbose_name": "colour",
                "verbose_name_plural": "colours",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="Fruit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text="The name of the fruit variety", max_length=20, verbose_name="name"),
                ),
                (
                    "category",
                    django_choices_field.fields.TextChoicesField(
                        example.fruit.models.FruitCategory,
                        help_text="The category of the fruit",
                        max_length=6,
                        verbose_name="category",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        help_text="The colour of this kind of fruit",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fruits",
                        to="fruit.color",
                        verbose_name="colour",
                    ),
                ),
            ],
            options={
                "verbose_name": "fruit",
                "verbose_name_plural": "fruits",
                "ordering": ("name",),
            },
        ),
    ]
